class Trustly::Exception::DataError < Exception
end
